// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: idl/comment.proto

package comment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CommentManagementClient is the client API for CommentManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommentManagementClient interface {
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error)
	DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error)
	QueryComments(ctx context.Context, in *QueryCommentsRequest, opts ...grpc.CallOption) (*QueryCommentsResponse, error)
}

type commentManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentManagementClient(cc grpc.ClientConnInterface) CommentManagementClient {
	return &commentManagementClient{cc}
}

func (c *commentManagementClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error) {
	out := new(CreateCommentResponse)
	err := c.cc.Invoke(ctx, "/comment.CommentManagement/CreateComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentManagementClient) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error) {
	out := new(DeleteCommentResponse)
	err := c.cc.Invoke(ctx, "/comment.CommentManagement/DeleteComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentManagementClient) QueryComments(ctx context.Context, in *QueryCommentsRequest, opts ...grpc.CallOption) (*QueryCommentsResponse, error) {
	out := new(QueryCommentsResponse)
	err := c.cc.Invoke(ctx, "/comment.CommentManagement/QueryComments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentManagementServer is the server API for CommentManagement service.
// All implementations must embed UnimplementedCommentManagementServer
// for forward compatibility
type CommentManagementServer interface {
	CreateComment(context.Context, *CreateCommentRequest) (*CreateCommentResponse, error)
	DeleteComment(context.Context, *DeleteCommentRequest) (*DeleteCommentResponse, error)
	QueryComments(context.Context, *QueryCommentsRequest) (*QueryCommentsResponse, error)
	mustEmbedUnimplementedCommentManagementServer()
}

// UnimplementedCommentManagementServer must be embedded to have forward compatible implementations.
type UnimplementedCommentManagementServer struct {
}

func (UnimplementedCommentManagementServer) CreateComment(context.Context, *CreateCommentRequest) (*CreateCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedCommentManagementServer) DeleteComment(context.Context, *DeleteCommentRequest) (*DeleteCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedCommentManagementServer) QueryComments(context.Context, *QueryCommentsRequest) (*QueryCommentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryComments not implemented")
}
func (UnimplementedCommentManagementServer) mustEmbedUnimplementedCommentManagementServer() {}

// UnsafeCommentManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentManagementServer will
// result in compilation errors.
type UnsafeCommentManagementServer interface {
	mustEmbedUnimplementedCommentManagementServer()
}

func RegisterCommentManagementServer(s grpc.ServiceRegistrar, srv CommentManagementServer) {
	s.RegisterService(&CommentManagement_ServiceDesc, srv)
}

func _CommentManagement_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentManagementServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.CommentManagement/CreateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentManagementServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentManagement_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentManagementServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.CommentManagement/DeleteComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentManagementServer).DeleteComment(ctx, req.(*DeleteCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentManagement_QueryComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentManagementServer).QueryComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.CommentManagement/QueryComments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentManagementServer).QueryComments(ctx, req.(*QueryCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommentManagement_ServiceDesc is the grpc.ServiceDesc for CommentManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommentManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "comment.CommentManagement",
	HandlerType: (*CommentManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateComment",
			Handler:    _CommentManagement_CreateComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _CommentManagement_DeleteComment_Handler,
		},
		{
			MethodName: "QueryComments",
			Handler:    _CommentManagement_QueryComments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idl/comment.proto",
}
